version: '3'
services:
  postgres-database:
    image: postgres:latest
    container_name: news-container
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql